const INIT_CART = 'INIT_CART';
const ADD_TO_CART = 'ADD_TO_CART';
const UPDATE_CART = 'UPDATE_CART';
const DELETE_CART = 'DELETE_CART';

export default {
  INIT_CART,
  ADD_TO_CART,
  UPDATE_CART,
  DELETE_CART,
};
